
add_library(vgui_controls STATIC
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/AnalogBar.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/AnimatingImagePanel.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/AnimationController.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/BitmapImagePanel.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/BuildFactoryHelper.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/BuildGroup.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/BuildModeDialog.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/Button.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/CheckButton.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/CheckButtonList.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/CircularProgressBar.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/ComboBox.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/consoledialog.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/ControllerMap.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/controls.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/DirectorySelectDialog.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/Divider.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/EditablePanel.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/ExpandButton.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/FileOpenDialog.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/FocusNavGroup.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/Frame.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/GraphPanel.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/HTML.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/Image.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/ImageList.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/ImagePanel.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/InputDialog.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/KeyRepeat.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/Label.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/ListPanel.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/ListViewPanel.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/Menu.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/MenuBar.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/MenuButton.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/MenuItem.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/MessageBox.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/MessageDialog.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/Panel.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/PanelListPanel.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/ProgressBar.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/ProgressBox.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/PropertyDialog.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/PropertyPage.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/PropertySheet.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/QueryBox.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/RadioButton.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/RichText.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/RotatingProgressBar.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/savedocumentquery.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/ScrollableEditablePanel.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/ScrollBar.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/ScrollBarSlider.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/SectionedListPanel.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/Slider.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/Splitter.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/subrectimage.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/TextEntry.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/TextImage.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/ToggleButton.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/Tooltip.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/ToolWindow.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/TreeView.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/TreeViewListControl.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/URLLabel.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/vgui_controls.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/WizardPanel.cpp"
	"${CMAKE_SOURCE_DIR}/src/ui/vgui2/vgui_controls/WizardSubPanel.cpp"
)


target_link_libraries(vgui_controls PUBLIC platform_config)
target_link_libraries(vgui_controls PUBLIC dead_wrapper)
target_link_libraries(vgui_controls PUBLIC vstdlib)
